version: '3'
services:
 mysqldb:
  image: mysql
  container_name:
   "mysql"
  restart: always
  ports:
   - 3306:3306
  environment: 
   MYSQL_ROOT_PASSWORD: Admin@2022
   MYSQL_DATABASE: ecom_batch1
   MYSQL_PASSWORD: Admin@2022
   MYSQL_ROOT_USER: root
 retail_User_Jen:
  image: retail-user-docker:latest
  container_name:
   "retail_user"
  restart: unless-stopped
 # restart: always
  ports:
   - 9001:9001
  build:
   context: ./
   dockerfile: Dockerfile
  depends_on:
   - mysqldb
  environment:
   SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/ecom_batch1"
   SPRING_DATASOURCE_USERNAME: root
   SPRING_DATASOURCE_PASSWORD: Admin@2022
   SPRING_JPA_HIBERNATE_DDL_AUTO: UPDATE
   SPRING_JPA_PROPERTIES_DIALECT: MYSQL57DIALECT