# version: '3.9'
# services: 
#  sql-sqerver-db: 
#   container_name: retail 
#   image: mysql
#   ports:
#    - "1234:1234"

version: '3'
services:
 mysqldb:
  image: mysql
  restart: always
  ports:
   - 3306:3306
  environment: 
   MYSQL_ROOT_PASSWORD: Admin@2022
   MYSQL_DATABASE: ecom_batch1
   MYSQL_PASSWORD: Admin@2022
   MYSQL_ROOT_USER: root
 retail_user_jen:
  image: retail-user-docker:latest
  ports:
   - 9001:9001
  build:
   context: ./
   dockerfile: Dockerfile
  depends_on:
   - mysqldb